### ISSUE TITLE
Any future plans?

### ISSUE THREAD

**Issue by dumblob** [elucent/clover#2]
Hi @elucent, long time no see :wink:.

I used to follow all news on Basil and Clover yet I see repo activity diminishing. Any future plans?

Also now when twitter, ehm X, completely blocked anonymous access I can not follow you any more. Your website is also inaccessible. Any suggestions how to stay in touch with you?

Thanks and enjoy!

**Comment by elucent** [comment]
Oh hey! I am still working on Basil and Clover when I have the time, just keeping it private for the time being for various reasons. I'm still active in the r/ProgrammingLanguages discord, so that's probably the best place to find me for now.

**Comment by dumblob** [comment]
Awesome, happy to hear that!

Will stay tuned :wink: (though admittedly my activity on GitHub is also close to zero in the past half a year - new job and family keeps me more than busy :shrug:).
